apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: job-tracker-app
data:
  # kv format
  SPRING_APPLICATION_NAME: "jobApplicationTrackerBackend"
  SPRING_DATA_MONGODB_HOST: "mongodb-service"
  SPRING_DATA_MONGODB_PORT: "27017"
  SPRING_DATA_MONGODB_DATABASE: "job-tracker-db"
  SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: "admin"

